### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nuchi** [epigramai/tfserving-python-predict-client#4]
This is fantastic! Are you releasing it for others to use? And if so, under which license?

**Comment by stianlp** [comment]
It's open source. Use it for whatever you find useful 👍

**Comment by nuchi** [comment]
Thank you, that's very generous! Would you consider releasing it under some license regardless? Github lists some good reasons to do so [here](https://help.github.com/articles/licensing-a-repository/).

Briefly:
> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

See also https://choosealicense.com/

**Comment by stianlp** [comment]
I'll look into it when I have time. For now, go ahead use it.

**Comment by nuchi** [comment]
Thanks! I ended up compiling the protos and writing a client on my own. It turned out not to be so bad once I realized that it was possible at all 🙂

**Comment by nuchi** [comment]
In case anyone is interested: https://github.com/nuchi/tf_pb_without_tf
